### All departamentos
GET http://localhost:3000/api/departamentos

### All empleados
GET http://localhost:3000/api/empleados

### Create new departamento 
POST http://localhost:3000/api/departamentos
Content-Type: application/json 

{
    "nombre":"UX",
    "ciudad":"Madrid"
}

### Create new empleado 
POST http://localhost:3000/api/empleados
Content-Type: application/json

{
    "nombre": "Juliana",
    "dni": "99828472D",
    "sexo": "F",
    "fecha_nacimiento": "1988-10-01",
    "salario": 2800,
    "cargo": "Jefecilla",
    "fk_departamento":3,
    "jefe_id": null

}

### Delete departament
DELETE http://localhost:3000/api/departamentos/7

### Delete empleado
DELETE http://localhost:3000/api/empleados/10

### Update departament 
PUT http://localhost:3000/api/departamentos/9
Content-Type: application/json

{
    "nombre":"UX",
    "ciudad":"Valencia"
}

### Update empleado
PUT http://localhost:3000/api/empleados/4
Content-Type: application/json

{
    "nombre": "Andreita",
    "dni": "76351834D",
    "sexo": "F",
    "fecha_nacimiento": "1978-09-01",
    "salario": 2700,
    "cargo": "Jefecilla",
    "fk_departamento":2,
    "jefe_id": 1

}

